title = "Chappy-Admin"
gitRepoUrl = "https://github.com/Camtheman300/Chappy-Admin"
gitSourceBranch = "master"

changelog = true

[[classOrder]]
section = "Core"
classes = [
	"MainModule",
	"Auth",
	"Hook",
	"Flux",
	"Process",
	"Registry",
	"Remote",
]

[[classOrder]]
section = "Interface"
classes = ["UI", "Checkbox"]

[[classOrder]]
section = "Utility"
classes = ["Util", "Logger", "Promise", "String"]

[docusaurus]
onBrokenLinks = "warn"
onBrokenMarkdownLinks = "warn"
trailingSlash = false
favicon = "/logo-dark.svg"
organizationName = "kohls-admin"
projectName = "main"
deploymentBranch = "gh-pages"
tagline = "Embrace creativity, not chaos."
url = "https://docs.kohl.gg"
baseUrl = "/"

[home]
enabled = true
includeReadme = false

[navbar]
title = ""

[[navbar.items]]
href = "https://github.com/Camtheman300/Chappy-Admin"
label = "FAQ"
position = "left"
target = "_self"
className = "no-link-icon"

[[navbar.items]]
href = "Discord Coming Soon"
label = "Discord"
position = "right"

[navbar.logo]
alt = "Chappy-Admin"
href = "https://github.com/Camtheman300/Chappy-Admin"
src = "/logo-load.svg"
srcDark = "/logo-load-dark.svg"
target = "_self"

[footer]
style = "light"
copyright = "© 2025 ChappyAdminSystems"
